### ISSUE TITLE
Reduce flavor ISOs

### ISSUE THREAD

**Issue by vinzv** [siduction/release-orga#1]
Flavors definitely to be made:
- Plasma
- xorg
- nox

Flavors to be discussed:
 - Xfce

Flavors to be thrown out:
- LXQt
- LXDE
- MATE
- Gnome
- Cinnamon

**Comment by fethomm** [comment]
I think it is a good idea to also keep LXQt, we have quite a few users there

**Comment by vinzv** [comment]
Okay for me, especially as there are not too many distributions with LXQt flavors.
I'd leave out Xfce therefore, as the target groups are pretty much the same here. And we really need to focus.

Any objections?

**Comment by fethomm** [comment]
Not from my side. I would also advise keeping the chance open to have all images we have as testbuilds for anyone who wants one of the images we intend to drop.

**Comment by vinzv** [comment]
Hm... but wouldn't that make dropping them obsolete as the images need to be maintained for testbuilds as well?

**Comment by fethomm** [comment]
I don't think so because it would not be mandatory to have all of them there at any time. From my experience, if a build fails, it can mostly be fixed by # the package in pyfll. If that is not the case, just don't build it.

**Comment by fethomm** [comment]
My motivation for that is that I don't want to leave users out in the cold, because I guess that is how they would feel.

**Comment by vinzv** [comment]
Decision taken:

:+1: Flavors definitely to be made:
- Plasma
- Xfce
- LXQt
- xorg
- nox

:-1: Flavors to be thrown out:
- LXDE
- MATE
- Gnome
- Cinnamon

Future releases will get one Live ISO and all other DEs via Calamares prospectively.
