### ISSUE TITLE
2022.1 Artwork

### ISSUE THREAD

**Issue by vinzv** [siduction/release-orga#12]
We need:
- a name
- artwork bits (wallpapers mostly)

**Comment by hhl** [comment]
I do not have a name yet, but I have done some work.

https://github.com/hhl/hhl/tree/master/siduction-exp

The sddm-theme-kde only works if you have plasma and the sddm breeze theme installed, so it is more a playing around with what is possible, not finished yet, I like the other (our) theme more, it's more clear.

Wallpaper and is the white horse of Uffington and in the back there is Stonehenge while the cranes are flying back (top left),
spring time, the birds coming back.

Icons, I only changed them slightly.

**Comment by vinzv** [comment]
A few thoughts on the wallpaper:
1. The green of the hills and siduction blue clash a bit
2. Both parts look as if they were stitched together. Do we want to keep the lens flare background?
3. Generally our wallpapers tend to be quite dark (also historically as I understand). Do we want to give them a bit more brightness?

Here's a quick draft:

![wallpaper_huegel](https://user-images.githubusercontent.com/74432/156264672-400ebf95-995a-4d95-99ff-2339f7de8f61.png)

**Comment by vinzv** [comment]
Regarding name/theme:
I like the overall hill/white horse of uffington/birds thing. As you say, spring time. Let's go further with that direction, maybe combined a to a jumping horse (German "spring").

**Comment by se7en-x230** [comment]
log7 here.

**Comment by vinzv** [comment]
https://github.com/siduction/wallpapers/blob/wintersky/draft/

**Comment by vinzv** [comment]
Done via https://github.com/siduction/wallpapers/commits/MoW
