### ISSUE TITLE
Plasma welcome page, maybe useful!

### ISSUE THREAD

**Issue by hhl** [siduction/release-orga#18]
https://invent.kde.org/plasma/plasma-welcome

In the future, next plasma release, after bookworm I guess, there will be the possibility to create a plasma -welcome-app, see link above.

Maybe this could be interesting, we can describe for example how to install media codecs to watch DVDs or Blu-rays or how to set up snapper with a one click option, and and and .......

But first we have to wait until plasma gets updated in debian, the time after bookworm.

**Comment by fethomm** [comment]
And then there is [Plasma Drawer](https://www.reddit.com/r/kde/comments/10dcpzp/i_didnt_like_how_any_of_the_fullscreen_app/)

**Comment by hhl** [comment]
Mh. we have softfreeze now!

**Comment by fethomm** [comment]
We have transition freeze, which only blocks transitions and freezes the toolchain.  Soft freeze sets in on Feb. 12, 5.27 debuts on Feb. 14. Afaik there were talks beforehand to be able to get 5.27 in, as soon as it hits stable. Let's see if that works.

**Comment by hhl** [comment]
I added a git repositorie https://github.com/siduction/plasma-welcome

There we can place pages for to present.

**Comment by hhl** [comment]
I close this because we do not use it
