### ISSUE TITLE
Remove simple-paste, it is really dead!

### ISSUE THREAD

**Issue by hhl** [siduction/release-orga#23]
simple-paste is dead, the server is dead, and the software too!

Please remove it from our sources and ISOs!

**Comment by hhl** [comment]
Ah, maybe we have to take look in our manual too!

**Comment by towo2099** [comment]
Hm, simple-paste is a Recommend in siduction-scripts.  
Should be enaugh to remove it from the repo, so the package siduction-scripts can't install it.

I have removed simple-paste from our repo.

**Comment by ak-li** [comment]
@hhl 
The manual does not contain an entry for the program simple-paste either.
You should be able to close this issue.

**Comment by hhl** [comment]
https://github.com/siduction/simple-paste

Well, it is still in our ISOs, see the manifestfile

` curl https://ftp.gwdg.de/pub/linux/siduction/iso/Standing_on_the_Shoulders_of_Giants/kde/siduction-2023.1.1-Standing_on_the_Shoulders_of_Giants-kde-amd64-202309091853.manifest | grep simple-paste
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0simple-paste                            0.2.1-1
100  132k  100  132k    0     0   245k      0 --:--:-- --:--:-- --:--:--  246k
`
so we have to remove it from our flavors.

I wasn't sure, if it was mentioned in our manual.

So I don't close this issue, it is still there.

**Comment by hhl** [comment]
And I would remove it from our ISO, but I can't find the place where it is!
I should be somewhere in pyfll, but .....

**Comment by towo2099** [comment]
since simple paste is not on any repo anymore, it's net included in newer isos.

```
srv/iso-build/cinnamon
towo:root533> grep simple *.manifest
libhtml-tokeparser-simple-perl         3.16-4
libipc-system-simple-perl              1.30-2
python3-pysimplesoap                   1.16.2-5
simple-scan                            44.0-1
```
