### ISSUE TITLE
Grub OS-Prober not enabled by default, re-enable it?

### ISSUE THREAD

**Issue by hhl** [siduction/release-orga#6]
* Boot menu entries for other operating systems are no longer generated by
    default.  To re-enable this, set GRUB_DISABLE_OS_PROBER=false in
    /etc/default/grub.

So, should we enable this by default?

**Comment by hhl** [comment]
Done, we enabled it by default,

**Comment by towo2099** [comment]
Instead of writing it to /etc/default/grub, i have put that to /etc/default/grub.d/siduction.cfg, which i have moved to settings-common. The next isos should contain that setting.
